; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = pico

[env]
lib_deps = 
	mikem/RadioHead @ ^1.120
	adafruit/DHT sensor library @ ^1.4.6
	kosme/arduinoFFT @ ^2.0.4
	earlephilhower/ESP8266Audio @ ^2.4.1

[env:pico]
platform = raspberrypi
board = pico
framework = arduino
upload_protocol = picotool
upload_port = E:\
; upload_port = COM6
upload_speed = 115200
monitor_port = COM6 ;
build_src_filter = +<Pi-pico/> -<Esp8266/> -<.git/>
lib_deps = 
	miguel5612/MQUnifiedsensor @ ^3.0.5
	mikem/RadioHead@^1.120
	adafruit/DHT sensor library@^1.4.6

[env:esp8266]
platform = espressif8266
framework = arduino
board = nodemcuv2
build_src_filter = +<Esp8266/> -<Pi-pico/> -<.git/>
monitor_speed = 115200
monitor_port = COM10 ;
upload_protocol = esptool
upload_speed = 921600
upload_port = COM10

lib_deps = 
	bblanchon/ArduinoJson @ ^7.4.2
	tzapu/WiFiManager @ ^2.0.17
	arduino-libraries/NTPClient @ ^3.2.1
	mikem/RadioHead@^1.120
	knolleary/PubSubClient@^2.8
	adafruit/DHT sensor library@^1.4.6


; [env:esp8266]
; platform = atmelavr
; board = uno
; framework = arduino
; monitor_speed = 115200
; upload_port = COM4
; build_src_filter = +<Esp8266/> -<Pi-pico/> -<.git/>
